// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh85E2UdF-uEGEpgrAQgRpN-z_g4qn96o',
    appId: '1:677346188413:web:052bca78b45c0cca936514',
    messagingSenderId: '677346188413',
    projectId: 'hikari-ia',
    authDomain: 'hikari-ia.firebaseapp.com',
    databaseURL: 'https://hikari-ia-default-rtdb.firebaseio.com',
    storageBucket: 'hikari-ia.firebasestorage.app',
    measurementId: 'G-R6G9HXH9SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEnmNDWRONQb3j-ZIx0Xb6JH56QyPBW44',
    appId: '1:677346188413:android:7a609af94cf80145936514',
    messagingSenderId: '677346188413',
    projectId: 'hikari-ia',
    databaseURL: 'https://hikari-ia-default-rtdb.firebaseio.com',
    storageBucket: 'hikari-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ5vpg9GlZpW-OKAHd2cwceWg8p79ND9Q',
    appId: '1:677346188413:ios:7e14dfbf7397d5e1936514',
    messagingSenderId: '677346188413',
    projectId: 'hikari-ia',
    databaseURL: 'https://hikari-ia-default-rtdb.firebaseio.com',
    storageBucket: 'hikari-ia.firebasestorage.app',
    iosBundleId: 'com.example.hikariProyect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ5vpg9GlZpW-OKAHd2cwceWg8p79ND9Q',
    appId: '1:677346188413:ios:7e14dfbf7397d5e1936514',
    messagingSenderId: '677346188413',
    projectId: 'hikari-ia',
    databaseURL: 'https://hikari-ia-default-rtdb.firebaseio.com',
    storageBucket: 'hikari-ia.firebasestorage.app',
    iosBundleId: 'com.example.hikariProyect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh85E2UdF-uEGEpgrAQgRpN-z_g4qn96o',
    appId: '1:677346188413:web:ef42259f6fbb1528936514',
    messagingSenderId: '677346188413',
    projectId: 'hikari-ia',
    authDomain: 'hikari-ia.firebaseapp.com',
    databaseURL: 'https://hikari-ia-default-rtdb.firebaseio.com',
    storageBucket: 'hikari-ia.firebasestorage.app',
    measurementId: 'G-7VS9NN9S3L',
  );
}
